source/accounts/urls.py
from django.urls import path

from accounts import views

app_name = "auth"
urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register, name="register"),
]

source/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from api import views

router = DefaultRouter()
router.register(r"users", views.UserViewSet)
router.register(r"todolists", views.TodoListViewSet)
router.register(r"todos", views.TodoViewSet)

app_name = "api"
urlpatterns = [
    path("", include(router.urls)),
]

source/approot/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.views.generic.base import TemplateView
from django.http import HttpResponse
from metatask import views
#from django.shortcuts import render,render_to_response

urlpatterns = [
    path('admin/', admin.site.urls),
    url('api/666', view=lambda e: HttpResponse('戏说不是胡说')),
    path('register', views.register),
    path('login', views.login),
    path('getUserInformation', views.getUserInformation),
    path('uploadHeadImg', views.uploadHeadImg),
    path('getHeadImg', views.getHeadImg),
    path('getGroupInformation', views.getGroupInformation),
    path('modifyUserInformation', views.modifyUserInformation),

]

source/lists/urls.py
from django.urls import path

from lists import views

app_name = "lists"
urlpatterns = [
    path("", views.index, name="index"),
    path("todolist/<int:todolist_id>/", views.todolist, name="todolist"),
    path("todolist/new/", views.new_todolist, name="new_todolist"),
    path("todolist/add/", views.add_todolist, name="add_todolist"),
    path("todo/add/<int:todolist_id>/", views.add_todo, name="add_todo"),
    path("todolists/", views.overview, name="overview"),

    path("grouplist/<int:grouplist_id>/", views.grouplist, name="grouplist"),
    path("grouplist/new/", views.new_grouplist, name="new_grouplist"),
    path("grouplist/add/", views.add_grouplist, name="add_grouplist"),
    path("group/add/<int:grouplist_id>/", views.add_group, name="add_group"),
]

source/todolist/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("lists.urls")),
    path("auth/", include("accounts.urls")),
    path("api/", include("api.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path("admin/", admin.site.urls),
]

source/todolist/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta charset="utf-8">
  <title>MetaTask</title>
  <meta name="description" content="Group todo list">
  <meta name="author" content="Jialei">
  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <!-- FONT
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link href='http://fonts.googleapis.com/css?family=Raleway:400,300,600' rel='stylesheet' type='text/css'>
  {% load static %}
  <!-- CSS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="stylesheet" type='text/css'
    href="https://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.2/normalize.min.css">
  <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.min.css">
  <link rel="stylesheet" type='text/css' href="{% static 'css/custom.css' %}">
  {% block css %}{% endblock %}
  <!-- Scripts
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <script type="text/javascript" src="{% static 'js/site.js' %}"></script>
  {% block js %}{% endblock %}
  <!-- Favicon
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="icon" type="image/png" href="{% static 'images/favicon.png' %}" />
</head>

<body>
  <!-- Primary Page Layout
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <div class="container">
    <!-- Navigation
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <div class="navbar-spacer"></div>
    <nav class="navbar">
      <div class="container">
        <ul class="navbar-list">
          <li class="navbar-item"><a class="navbar-link" href="{% url 'lists:index' %}">Metatask</a></li>
          <!--add by jialei -->
          <!--
          <form action="{% url 'lists:new_grouplist' %}" method=post>
          </form>
          {% if user.is_authenticated %}
          {% for grouplist in user.grouplist.all %}
          <li class="navbar-item"><a class="navbar-link" href="{% url 'lists:grouplist' grouplist_id=grouplist.id %}" ,
              style="text-align:center;">Group</a></li>
          {% endfor %}
          {% endif %}
          -->
          {% if not user.is_authenticated %}
          <li class="navbar-item">
            <a class="navbar-link" href="{% url 'auth:login' %}">Login</a>
          </li>
          {% else %}
          <li class="navbar-item">
            <a class="navbar-link" href="#" data-popover="#moreNavPopover">{{ user.username }}</a>
            <div id="moreNavPopover" class="popover">
              <ul class="popover-list">
                <li class="popover-item">
                  <a class="popover-link" href="{% url 'lists:overview' %}">Your Groups</a>
                </li>
                <li class="popover-item">
                  <a class="popover-link" href="{% url 'auth:logout' %}">logout</a>
                </li>
              </ul>
            </div>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    {% block body %}{% endblock %}
  </div>
  <!-- End Document
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
</body>

</html>